version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DB_URL=mysql://root:P4ssw0rd@mysql_db:3306/staycation
      - POSTGRESQL_DB_URL=postgresql://postgres:P4ssw0rd@postgres_db:5432/staycation
    depends_on:
      - mysql_db
      - postgres_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: staycation
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: staycation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data: